title: The Experience Lab
description: Understanding the emotions behind an experience – BUas
remote_theme: just-the-docs/just-the-docs@v0.10.0

url: "https://saitdurgun.github.io"
baseurl: "/experiencelab-buas"

logo: "https://saitdurgun.github.io/experiencelab-buas/buas_logo.jpg"
