title: The Experience Lab
description: Understanding the emotions behind an experience — BUas
theme: just-the-docs
url: "https://saitdurgun.github.io"
baseurl: "/experiencelab-buas"

aux_links:
  BUas Website: "https://www.buas.nl/experiencelab"
aux_links_new_tab: true
